name: Download and Upload ZIP to Telegram

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download ZIP file
        run: |
          curl -L -o xs.zip https://jihulab.com/fourd/FourD/-/raw/main/local/单线路.zip
          # 验证文件是否存在
          file 单线路.zip

      - name: Upload to Telegram
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TG_BOT_TOKEN/sendDocument -F chat_id=$TG_CHAT_ID -F document=@单线路.zip
