name: Download and Upload ZIP to Telegram

on:
  schedule:
    - cron: "0 * * * *"  # 每小时的第 0 分钟运行一次

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download ZIP file
        run: |
          curl -L -o xs.zip https://jihulab.com/fourd/FourD/-/raw/main/local/单线路.zip

      - name: Upload to Telegram
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TG_BOT_TOKEN/sendDocument -F chat_id=$TG_CHAT_ID -F document=@xs.zip
